//! Typed NES CPU-RAM image with generated accessors.
//!
//! `Ram` owns the 2 KiB of NES internal RAM (`$0000-$07FF`; every address in
//! `ram-map.toml` falls in this range). Named getters/setters
//! (`ram.link_hp()`, `ram.set_link_hp()`, `ram.enemy(slot).x()`, ...) are
//! generated at build time by `crates/z2-core/build.rs` from
//! `ram-map.toml`; each carries a doc comment with its address,
//! disassembly label, source and verification flag.
//!
//! Ownership note: this `Ram` (and `crate::facts::Game`) is defined locally
//! so the asset loader stays independent. Interop with the
//! loader/oracle is byte-based: [`Ram::from_slice`] / [`Ram::as_slice`]
//! move whole 2 KiB images across the boundary without sharing types.
//!
//! [`Ram::read`] / [`Ram::write`] mask the address to 11 bits, modelling the
//! NES RAM mirrors (`$0000-$07FF` mirrored through `$1FFF`).

use std::error::Error;
use std::fmt;

/// Error from [`Ram::from_slice`] when the byte count is not one full RAM.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct RamError {
    /// Bytes required (always [`Ram::LEN`]).
    pub expected: usize,
    /// Bytes actually supplied.
    pub got: usize,
}

impl fmt::Display for RamError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(
            f,
            "RAM image must be {} bytes, got {}",
            self.expected, self.got
        )
    }
}

impl Error for RamError {}

/// NES internal CPU RAM image (`$0000-$07FF`).
///
/// Named accessors (e.g. [`Ram::link_hp`], [`Ram::enemy`]) are generated
/// into the `include!` below; see `ram-map.toml` for the address table.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Ram {
    mem: [u8; Self::LEN],
}

impl Default for Ram {
    fn default() -> Self {
        Self::new()
    }
}

impl Ram {
    /// Size of the NES internal RAM image in bytes.
    pub const LEN: usize = 0x0800;

    /// Zeroed RAM image.
    pub fn new() -> Self {
        Self {
            mem: [0; Self::LEN],
        }
    }

    /// Copy a raw 2 KiB image (e.g. from the asset loader or a snapshot
    /// file) into a `Ram`.
    pub fn from_slice(bytes: &[u8]) -> Result<Self, RamError> {
        if bytes.len() != Self::LEN {
            return Err(RamError {
                expected: Self::LEN,
                got: bytes.len(),
            });
        }
        let mut ram = Self::new();
        ram.mem.copy_from_slice(bytes);
        Ok(ram)
    }

    /// Borrow the whole image (e.g. to hand to the loader, a snapshot
    /// writer, or [`crate::facts::Game`]).
    pub fn as_slice(&self) -> &[u8; Self::LEN] {
        &self.mem
    }

    /// Raw read with NES mirroring (`$0000-$07FF` repeats to `$1FFF`).
    pub fn read(&self, addr: u16) -> u8 {
        self.mem[(addr & 0x07FF) as usize]
    }

    /// Raw write with NES mirroring.
    pub fn write(&mut self, addr: u16, value: u8) {
        self.mem[(addr & 0x07FF) as usize] = value;
    }
}

// Generated by crates/z2-core/build.rs from ram-map.toml:
// address constants (ADDR_*/BASE_*), Ram::{name,set_name} accessors,
// Ram::enemy/enemy_mut + EnemyRef(+Mut), Ram::projectile/projectile_mut
// + ProjectileRef(+Mut), and indexed spell()/item() accessors.
include!(concat!(env!("OUT_DIR"), "/ram_gen.rs"));
