//! Routine trap table + trap log + divergence type.
//!
//! # Model
//!
//! As routines are hand-ported to Rust, each registers a [`TrapFn`] at its
//! 6502 entry address in the [`TrapTable`]. When the interpreter executes
//! `JSR`/`JMP`/a vector to a trapped address it calls the Rust function and
//! emulates the matching return (`RTS`/`RTI`), so the 6502 stack stays
//! balanced and unported callers never notice the substitution.
//!
//! # `ports.toml` (read-only)
//!
//! The canonical routine ledger lives at the workspace root (`ports.toml`,
//! generated by `cargo xtask ledger` — never edited here). [`routine_addrs`] parses
//! its `[[routine]]` entries (`name`/`bank`/`addr`) with a dependency-free
//! line parser so tests and tooling can cross-check trap addresses against
//! the ledger without new dependencies. A freshly built [`TrapTable`] holds
//! **zero traps** (everything interprets); ported routines opt in with
//! [`TrapTable::register`].
//!
//! # Bank aliasing caveat (M1)
//!
//! Traps are keyed by 16-bit CPU address. PRG banks alias the same CPU
//! addresses (`$8000-$BFFF`), so a trap on a banked address would also fire
//! for same-named routines in the other banks. Until mapper-aware
//! routing lands, only trap routines in the fixed bank (`$C000-$FFFF`,
//! bank 7) or RAM-resident vectors. [`TrapInfo::bank`] records the ledger
//! bank for that future routing (and for human review).
//!
//! # A/B verification
//!
//! Any trapped address can run untrapped without unregistering:
//! [`TrapTable::set_untrapped`] (or the global [`TrapTable::enabled`] kill
//! switch) makes the interpreter execute the original bytes instead. The
//! `interp_traps` test replays synthetic routines both ways and asserts
//! identical state.
//!
//! # Trap log → divergence attribution
//!
//! Every fired trap appends a [`TrapRecord`] (address, routine name, frame)
//! to the [`TrapLog`] ring ([`TRAP_LOG_CAP`] entries). [`Divergence`] — a
//! local mirror of `z2-verify::oracle::Divergence` (this crate
//! must not depend on `z2-verify`; keep the shapes in sync by hand) —
//! carries `last_writer: Option<String>` naming the most recent routine, so
//! a lockstep mismatch points at the ported routine that wrote last.

use std::collections::{HashMap, HashSet, VecDeque};

use crate::game::Game;

/// Rust implementation of one ported routine.
///
/// Receives the whole [`Game`] (RAM mirror, WRAM, CPU registers, PPU/APU
/// façades) and must replicate the observable effects of the original
/// bytes: memory writes **and** the register/flag state the original `RTS`
/// (or tail-call `JMP`) would leave behind. The interpreter handles the
/// return itself (emulated `RTS`/`RTI`); the function must not touch the
/// 6502 return address on the stack. A routine that ends in a tail `JMP`
/// (or branches into code that stays with the interpreter) asks for the
/// transfer instead of faking it:
/// [`Game::trap_jump`](crate::game::Game::trap_jump) makes the dispatcher
/// continue at that address once the function returns — firing the
/// target's own trap when it has one — with the stack left exactly as the
/// original `JMP` would have (see [`TrapExit`]).
///
/// Timing: the function itself does not touch [`crate::cpu::Cpu::cycles`];
/// the dispatch path ([`Game::fire_trap`](crate::game::Game::fire_trap))
/// advances `cycles` by the trap's [`TrapInfo::cycles`] cost on every fire,
/// so trapped runs consume the same frame budget as interpretation (see
/// cycle-accounting docs on [`TrapTable::register_with_cycles`]).
pub type TrapFn = fn(&mut Game);

/// How control leaves a fired trap
/// ([`Game::fire_trap`](crate::game::Game::fire_trap)).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[must_use = "the dispatch site must emulate the return or continue at the jump target"]
pub enum TrapExit {
    /// The body — or the last body of a tail-jump chain — returned: emulate
    /// the routine's `RTS` (`JSR`/`JMP` entry) or `RTI` (vector entry).
    Return,
    /// The body tail-jumped ([`Game::trap_jump`](crate::game::Game::trap_jump))
    /// to an address with no trap: continue interpreting there. The stack
    /// already holds what the original `JMP` left (the caller's frame stays
    /// underneath for the target's own `RTS`; nothing was pushed).
    Jump(u16),
}

/// One trapped routine.
#[derive(Debug, Clone, Copy)]
pub struct TrapInfo {
    /// Ledger name (e.g. `"rng_advance"` or the `ports.toml` routine name).
    pub name: &'static str,
    /// CPU entry address.
    pub addr: u16,
    /// Ledger bank, when known (informational until bank-aware routing).
    pub bank: Option<u8>,
    /// The ported implementation.
    pub func: TrapFn,
    /// 6502 cycles the original bytes would have consumed, **including**
    /// the final `RTS`/`RTI` (6) but **excluding** the caller's `JSR`/`JMP`/
    /// `BRK`/vector entry (already counted by the dispatch site in
    /// `cpu.rs`). Tail-call trampolines ending in `JMP (ind)` (e.g.
    /// `$D382`/`$D385`) include that final `JMP` (5) and no `RTS`.
    ///
    /// `0` = unknown/uncosted (pre-cycle-accounting behaviour: time-free).
    pub cycles: u64,
}

/// Address → Rust-implementation table.
///
/// Empty by default (zero traps: pure interpretation). Register ported
/// routines with [`TrapTable::register`].
#[derive(Debug, Default)]
pub struct TrapTable {
    entries: HashMap<u16, TrapInfo>,
    /// Trapped addresses temporarily running as raw ASM (A/B toggle).
    untrapped: HashSet<u16>,
    /// Global kill switch. `false` = whole table untrapped (pure interp).
    pub enabled: bool,
}

impl TrapTable {
    /// Empty table with the global switch on (still zero traps).
    pub fn new() -> Self {
        Self {
            entries: HashMap::new(),
            untrapped: HashSet::new(),
            enabled: true,
        }
    }

    /// Register a ported routine. Replaces any previous entry at `addr`.
    ///
    /// Backward-compat wrapper: keeps the pre-cycle-accounting call shape
    /// so all existing registrations keep compiling. The stored cost is
    /// [`default_trap_cycles`] for `addr` (`0` for unknown addresses):
    /// known boot-path bank-7 traps pick up their measured/counted costs
    /// automatically (central table, since `bank7_*.rs` are read-only for
    /// the cycle-charging workstream), unknown traps stay time-free.
    /// Use [`TrapTable::register_with_cycles`] to override explicitly.
    pub fn register(&mut self, name: &'static str, bank: Option<u8>, addr: u16, func: TrapFn) {
        let cycles = default_trap_cycles(addr);
        self.register_with_cycles(name, bank, addr, func, cycles);
    }

    /// Register a ported routine with an explicit cycle cost (see
    /// [`TrapInfo::cycles`] for the included/excluded convention).
    ///
    /// Replaces any previous entry at `addr`. Prefer this when the cost
    /// is measured for a specific setup (variable-path routines) or when
    /// overriding the central [`default_trap_cycles`] table.
    pub fn register_with_cycles(
        &mut self,
        name: &'static str,
        bank: Option<u8>,
        addr: u16,
        func: TrapFn,
        cycles: u64,
    ) {
        self.entries.insert(
            addr,
            TrapInfo {
                name,
                addr,
                bank,
                func,
                cycles,
            },
        );
    }

    /// Remove the trap at `addr` (returns `true` when one existed).
    pub fn unregister(&mut self, addr: u16) -> bool {
        self.untrapped.remove(&addr);
        self.entries.remove(&addr).is_some()
    }

    /// Look up the trap at `addr` (ignores the untrapped toggles).
    pub fn get(&self, addr: u16) -> Option<&TrapInfo> {
        self.entries.get(&addr)
    }

    /// Number of registered traps.
    pub fn len(&self) -> usize {
        self.entries.len()
    }

    /// Whether any traps are registered.
    pub fn is_empty(&self) -> bool {
        self.entries.is_empty()
    }

    /// Mark `addr` to run untrapped (`true`) or trapped (`false`) without
    /// unregistering — the A/B verification toggle.
    pub fn set_untrapped(&mut self, addr: u16, untrapped: bool) {
        if untrapped {
            self.untrapped.insert(addr);
        } else {
            self.untrapped.remove(&addr);
        }
    }

    /// Whether `addr` currently runs untrapped via the A/B toggle.
    pub fn is_untrapped(&self, addr: u16) -> bool {
        self.untrapped.contains(&addr)
    }

    /// Whether control transferred to `addr` should invoke Rust: the global
    /// switch is on, a trap is registered, and the A/B toggle is off.
    pub fn is_trapped(&self, addr: u16) -> bool {
        self.enabled && self.entries.contains_key(&addr) && !self.untrapped.contains(&addr)
    }

    /// Iterate registered traps (arbitrary order).
    pub fn iter(&self) -> impl Iterator<Item = &TrapInfo> {
        self.entries.values()
    }
}

// ------------------------------------------------- per-trap cycle costs
//
// Time-collapse fix: traps were state-exact but cycle-free, so a
// trapped boot executed ~33k cycles of clears/erases in ~10 host cycles and
// ran a frame ahead of the oracle (trapped f=3 `$0000` vs untrapped f=7).
// Each trap now carries the 6502 cycles its bytes would have consumed
// ([`TrapInfo::cycles`]: body + final `RTS`/`RTI`, caller `JSR`/`JMP`
// excluded). [`Game::fire_trap`](crate::game::Game::fire_trap) adds the
// cost on every fire, so `run_budget`/`Cpu::run_cycles` frame budgets and
// the absolute-cycle vblank cadence (`FIRST_VBLANK_AT + k*VBLANK_PERIOD`)
// see the same clock as interpretation.
//
// Where the cost lands in dispatch (`cpu.rs`):
// * `JSR abs` (`$20`): entry `cost = 6` + `fire_trap` cycles (includes RTS).
// * `JMP abs/ind` (`$4C`/`$6C`): entry `cost = 3`/`5` + `fire_trap` cycles
//   (includes RTS; the old extra `+6` for the emulated `RTS` is removed to
//   avoid double-counting — the cost already contains it).
// * `BRK`/`NMI`/`IRQ` vectors: service `+7` + `fire_trap` cycles (includes
//   `RTI`); `RESET`: `+7` + body (no return).
// * `run_budget` (`game.rs`) and `Cpu::run_cycles` loop on absolute
//   `cpu.cycles`, so charged traps reduce the interpreter steps per frame
//   back to untrapped pacing; the vblank hook points do not move.
//
// Method per entry (`measured` = `try_call_asm` cycle-delta on the ROM or
// exact excerpt bytes vs the Rust port, same seeds; `counted` = instruction
// count from `third_party/z2disassembly/src/prg7.asm` under the `cpu.rs`
// cost model, assuming no page-cross extra — all boot loops are short
// backward branches in-page and all `abs,X` accesses stay in-page).
// Fixed-path routines are exact; variable-path routines use the common-case
// (documented) branch and note the alternate.
//
/// Central cycle table for the fixed-bank boot traps.
///
/// [`TrapTable::register`] consults this so the 100+ existing
/// `trap_register` call sites keep compiling unchanged while the boot path
/// picks up real costs (the `bank7_*.rs` registrars are read-only for this
/// workstream). Returns `0` for unknown addresses (time-free, pre-fix
/// behaviour). Use [`TrapTable::register_with_cycles`] to override.
pub fn default_trap_cycles(addr: u16) -> u64 {
    match addr {
        // MMC1 serial switchers (`prg7.asm $FF9D/$FFB1/$FFCC`): 5x STA abs
        // (4) + 4x LSR A (2) + RTS (6) = 34. Counted; measured 34 via
        // excerpt harness (A corners $00/$0F/$1F).
        0xFF9D => 34, // ConfigureMMC1
        0xFFB1 => 34, // SwapCHR
        0xFFCC => 34, // SwapPRG
        // LDA #$00 (2) + BEQ taken (3) + SwapPRG (34) = 39. Counted.
        0xFFC5 => 39, // SwapToPRG0
        // LDA $0769 abs (4) + SwapPRG (34) = 38. Counted.
        0xFFC9 => 38, // SwapToSavedPRG
        // Controller capture (`$D367`): prologue 14 + 7x27 + 26 + RTS 6 =
        // 235. Counted; measured 235 on pad corners ($00/$FF/$A5).
        0xD367 => 235, // Controllers_Input_Capture
        // Debounced input (`$D346`, agree path): JSR 6 + 235 + LDA 3 + STA
        // 3 + JSR 6 + 235 + LDA 3 + CMP 3 + BNE n-taken 2 + LDX 2 + 27 + 26
        // + RTS 6 = 557. Counted (debounce loop adds ~250/round on
        // disagreement; blank/steady pads agree first try). Measured 557.
        0xD346 => 557, // Controllers_Input (each extra debounce round adds 497 in the port)
        // Reset_Memory_Ranges (`$D281` falls into `$D29C`): 3x page-clear
        // 2563 + $D29C 7605 = 15294 incl. RTS. Counted; measured 15294 via
        // ROM harness (salted RAM). Per-page: LDX 2 + TXA 2 + 256x STA
        // abs,X 5 + 256x DEX 2 + 255x BNE-taken 3 + 1x n-taken 2 = 2563.
        0xD281 => 15294, // Reset_Memory_Ranges
        // `$D29C`: 2x page-clear 5126 + zp loop 2463 + LDX 2 + 2x STX abs 8
        // + RTS 6 = 7605. Counted; measured 7605. Zp loop: 224x (STA zp,X
        // 4 + DEX 2 + CPX #imm 2 + BNE 3/2).
        0xD29C => 7605, // Set_Memory_300_4FF_and_00_DF_to_Zero
        // Sprite hide (`$D24C`): LDY 2 + BEQ taken 3 + LDA 2 + 63x16 + 15 +
        // RTS 6 = 1036 (64 stores). Counted; measured 1036.
        0xD24C => 1036, // Remove_All_Sprites
        // `$D250`: LDY 2 + LDA 2 + 62x16 + 15 + RTS 6 = 1017 (63 stores,
        // sprite 0 preserved). Counted; measured 1017.
        0xD250 => 1017, // Remove_All_Sprites_except_Sprite0
        // Fill screen (`$D2BE`): prologue 24 + 3-page loop 6923 + 192x tail
        // 2111 + LDA 2 + 64x tail 575 + RTS 6 = 9641. Counted; measured
        // 9641 (A=$20/$24).
        0xD2BE => 9641, // Fill_Screen_F4
        // Erase table 1 (`$D261`): LDA 2 + JMP 3 + Fill 9641 = 9646.
        0xD261 => 9646, // Erase_Name_Table_1
        // Erase table 0 (`$D263`): JMP 3 + Fill 9641 = 9644.
        0xD263 => 9644, // Erase_Name_Table_0
        // Erase both (`$D266`): JSR 6 + 9646 + LDA 2 + JSR 6 + 9644 + LDA 2
        // + STA zp 3 + STA zp 3 + STA abs 4 + 2x STA $2005 4 + INC abs 6 +
        // RTS 6 = 19336. Counted; measured 19336.
        0xD266 => 19336, // Erase_Name_Tables_0and1
        // PPU queue drain (`$D2EC`): 18 for the empty queue (LDY 2 + LDA
        // (zp),Y 5 + CMP 2 + BEQ taken 3 + RTS 6). Counted; measured 18.
        // Non-empty queues add their per-entry cost inside the port
        // (`drain_update_queue` counts every entry, byte and branch).
        0xD2EC => 18, // LD2EC_PPU_Queue_Drain
        // Sideview palette (`$FD82`): prologue 46 + 7 rows (6x47 + 46) +
        // LDA 2 + STY abs 4 + RTS 6 = 386. Counted; measured 386.
        0xFD82 => 386, // code52_Sideview_Palette
        // Trampolines (no RTS — tail `JMP (ind)` 5): `$D385` = ASL 2 + TAY
        // 2 + PLA 4 + STA 3 + PLA 4 + STA 3 + INY 2 + LDA (zp),Y 5 + STA 3
        // + INY 2 + LDA 5 + STA 3 + JMP ind 5 = 43; `$D382` adds LDA $073D
        // abs 4 = 47. Counted; measured 43/47 on synthetic tables.
        0xD385 => 43, // PullAddr_JMP
        0xD382 => 47, // JmpToRoutine_073D
        // Detectors (common same-path; changed-path in parens):
        // `$D158`: STA abs 4 + RTS 6 = 10. Counted.
        0xD158 => 10, // LD158_Macro_Select
        // `$D15C`: LDA 4 + CMP abs 4 + STA 4 + BNE n-taken 2 + RTS 6 = 20
        // (changed: +LDY 2 + STY 4 + RTS = 27). Counted; same-path tabled.
        0xD15C => 20, // LD15C_Dialog_Change (changed path adds 7 in the port)
        // `$D168`: LDA 4 + CMP 4 + STA 4 + BNE n-taken 2 + RTS 6 = 20
        // (changed 37). Counted; same-path tabled (boot steady-state).
        0xD168 => 20, // LD168_Mode_Change (changed path adds 17 in the port)
        // `$D174` same-path: LDA 4 + CMP 4 + STA 4 + BEQ taken 3 + RTS 6 =
        // 21 (changed path calls Remove_All_Sprites: 1092). Counted;
        // same-path tabled.
        0xD174 => 21, // LD174_Stage_Change (changed path adds 1071 in the port)
        // Title `LCF05` (`prg7.asm $CF05`, fires via `JMP LCF05` tail-calls
        // in early boot): INC $0736 abs (6) + RTS (6) = 12. Counted.
        0xCF05 => 12, // LCF05_Mode_Inc
        _ => 0,
    }
}

// ------------------------------------------------- ports.toml parsing

/// One `[[routine]]` entry from `ports.toml`: ledger bank, CPU address,
/// routine name.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct LedgerRoutine {
    /// Ledger bank (PRG bank number).
    pub bank: u8,
    /// CPU address of the routine entry.
    pub addr: u16,
    /// Routine name (repeats across banks; `(bank, name)` is the key).
    pub name: String,
    /// `code`/`data`/`jump-table`/… (kept for filtering; may be empty).
    pub kind: String,
    /// `unported`/`ported`/`verified` (may be empty on old ledgers).
    pub status: String,
}

fn parse_quoted(value: &str) -> Option<String> {
    let v = value.trim();
    if v.len() >= 2 && v.starts_with('"') && v.ends_with('"') {
        Some(v[1..v.len() - 1].to_string())
    } else {
        None
    }
}

fn parse_number(value: &str) -> Option<u32> {
    let v = value.trim();
    if let Some(hex) = v.strip_prefix("0x").or_else(|| v.strip_prefix("0X")) {
        u32::from_str_radix(hex, 16).ok()
    } else {
        v.parse::<u32>().ok()
    }
}

/// Parse the `[[routine]]` entries of a `ports.toml` text.
///
/// Dependency-free line parser for exactly the schema documented at the top
/// of `ports.toml`: `[[routine]]` sections with `name = "..."`,
/// `bank = N`, `addr = 0xNNNN` (+ `kind`/`status` when present). Unknown
/// keys and other sections are ignored so ledger additions never break the
/// interpreter build. Malformed `[[routine]]` blocks (missing name/bank /
/// addr) are skipped, not fatal: the ledger is advisory to execution.
pub fn routine_addrs(text: &str) -> Vec<LedgerRoutine> {
    let mut out = Vec::new();
    let mut in_routine = false;
    let mut name: Option<String> = None;
    let mut bank: Option<u32> = None;
    let mut addr: Option<u32> = None;
    let mut kind = String::new();
    let mut status = String::new();

    let flush = |out: &mut Vec<LedgerRoutine>,
                 name: &mut Option<String>,
                 bank: &mut Option<u32>,
                 addr: &mut Option<u32>,
                 kind: &mut String,
                 status: &mut String| {
        if let (Some(n), Some(b), Some(a)) = (name.take(), bank.take(), addr.take()) {
            if b <= u8::MAX as u32 && a <= u16::MAX as u32 {
                out.push(LedgerRoutine {
                    bank: b as u8,
                    addr: a as u16,
                    name: n,
                    kind: core::mem::take(kind),
                    status: core::mem::take(status),
                });
                return;
            }
        }
        kind.clear();
        status.clear();
    };

    for line in text.lines() {
        let t = line.trim();
        if t.is_empty() || t.starts_with('#') {
            continue;
        }
        if t.starts_with("[[") {
            if in_routine {
                flush(
                    &mut out,
                    &mut name,
                    &mut bank,
                    &mut addr,
                    &mut kind,
                    &mut status,
                );
            }
            in_routine = t == "[[routine]]";
            name = None;
            bank = None;
            addr = None;
            kind.clear();
            status.clear();
            continue;
        }
        if !in_routine {
            continue;
        }
        let Some(eq) = t.find('=') else { continue };
        let (k, v) = (t[..eq].trim(), t[eq + 1..].trim());
        match k {
            "name" => {
                if let Some(s) = parse_quoted(v) {
                    name = Some(s);
                }
            }
            "bank" => bank = parse_number(v),
            "addr" => addr = parse_number(v),
            "kind" => {
                if let Some(s) = parse_quoted(v) {
                    kind = s;
                }
            }
            "status" => {
                if let Some(s) = parse_quoted(v) {
                    status = s;
                }
            }
            _ => {}
        }
    }
    if in_routine {
        flush(
            &mut out,
            &mut name,
            &mut bank,
            &mut addr,
            &mut kind,
            &mut status,
        );
    }
    out
}

// ------------------------------------------------- trap log

/// Ring capacity: last N routines executed (with frame numbers).
pub const TRAP_LOG_CAP: usize = 64;

/// One fired trap.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct TrapRecord {
    /// CPU entry address that was trapped.
    pub addr: u16,
    /// Routine name from the [`TrapTable`].
    pub name: String,
    /// [`Game::frame_count`] when the trap fired.
    pub frame: u64,
}

impl TrapRecord {
    /// `"name@$ADDR"` attribution string for [`Divergence::last_writer`].
    pub fn attribution(&self) -> String {
        format!("{}@${:04X}", self.name, self.addr)
    }
}

/// Ring buffer of the last [`TRAP_LOG_CAP`] fired traps (oldest evicted).
#[derive(Debug, Clone, Default)]
pub struct TrapLog {
    buf: VecDeque<TrapRecord>,
}

impl TrapLog {
    /// Empty log.
    pub fn new() -> Self {
        Self {
            buf: VecDeque::with_capacity(TRAP_LOG_CAP),
        }
    }

    /// Record one fired trap (evicts the oldest past capacity).
    pub fn push(&mut self, addr: u16, name: &str, frame: u64) {
        if self.buf.len() >= TRAP_LOG_CAP {
            self.buf.pop_front();
        }
        self.buf.push_back(TrapRecord {
            addr,
            name: name.to_string(),
            frame,
        });
    }

    /// Most recent record, if any.
    pub fn last(&self) -> Option<&TrapRecord> {
        self.buf.back()
    }

    /// Number of records retained.
    pub fn len(&self) -> usize {
        self.buf.len()
    }

    /// Whether the log is empty.
    pub fn is_empty(&self) -> bool {
        self.buf.is_empty()
    }

    /// Oldest-first iterator.
    pub fn iter(&self) -> impl Iterator<Item = &TrapRecord> {
        self.buf.iter()
    }

    /// Clear all records.
    pub fn clear(&mut self) {
        self.buf.clear();
    }
}

// ------------------------------------------------- divergence

/// First lockstep mismatch between [`Game`] and the oracle.
///
/// Local mirror of `z2-verify::oracle::Divergence`. This
/// crate must not depend on `z2-verify`; keep the two shapes in sync by
/// hand. `last_writer` names the most recently trapped routine
/// (`"name@$ADDR"` from the [`TrapLog`]) so a mismatch points at the ported
/// routine that wrote last; `None` means no trap had fired yet (pure
/// interpreter drift or oracle/test bug).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Divergence {
    /// Frame index where the mismatch was found.
    pub frame: u64,
    /// Absolute address of the first differing byte (`0x0000-0x07FF` = RAM,
    /// `0x6000-0x7FFF` = WRAM).
    pub addr: u16,
    /// Oracle (expected) byte.
    pub expected: u8,
    /// `Game` (actual) byte.
    pub actual: u8,
    /// Attribution from the trap log.
    pub last_writer: Option<String>,
}

impl core::fmt::Display for Divergence {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        write!(
            f,
            "divergence at frame {}: ${:04X} oracle={:02X} game={:02X} last_writer={}",
            self.frame,
            self.addr,
            self.expected,
            self.actual,
            self.last_writer.as_deref().unwrap_or("<untrapped>")
        )
    }
}

impl std::error::Error for Divergence {}
