//! Template packs rendered straight from CHR pages.
//!
//! A template is a complete, loadable pack: one page sheet per requested CHR
//! page plus a `pack.json` that maps every non-blank tile. An artist opens a
//! sheet, paints over the cells in place (keeping the grid) and the directory
//! loads unchanged as an HD pack.
//!
//! **Legal:** templates are derived from ROM bytes. Write them only to a
//! directory outside the repository; never commit or share unpainted cells.

use std::collections::BTreeSet;
use std::fmt;

use crate::chr::{chr_page, paint_page_sheet, CHR_PAGES};
use crate::pack::{PackManifest, SheetEntry, PACK_FORMAT, PACK_MANIFEST, PACK_VERSION};
use crate::palette::MasterPalette;
use crate::png_io::{encode_png_rgba, PngError, RgbaImage};
use crate::MAX_SCALE;

/// tEXt keyword stamped on every template PNG (the pre-commit hook greps it).
pub const TEMPLATE_TEXT_KEY: &str = "z2rs-template";
/// tEXt value stamped on every template PNG.
pub const TEMPLATE_TEXT_VALUE: &str = "rendered from ROM CHR; never commit (see LEGAL.md)";
/// Marker file written beside every template pack.
pub const MARKER_FILE: &str = "TEMPLATE-ROM-DERIVED.txt";
/// Contents of [`MARKER_FILE`].
pub const MARKER_TEXT: &str = "This directory was generated by z2rs from the CHR graphics of your own \
Zelda II ROM. The sheets are ROM-derived: never commit them to the z2rs repository and never share \
cells you have not repainted yourself. Paint over the cells in place (keep the 16x16 grid), then load \
the directory with --hd-pack. Delete this file only once every cell you ship is your own art.\n";
/// Default colours for sub-palette entries 1, 2, 3 when no palette is given.
pub const GRAY_RAMP: [[u8; 3]; 3] = [[0x55, 0x55, 0x55], [0xAA, 0xAA, 0xAA], [0xFF, 0xFF, 0xFF]];

/// Inputs for [`template_from_chr`].
#[derive(Debug, Clone, Copy)]
pub struct TemplateOptions<'a> {
    /// Pack `name`.
    pub name: &'a str,
    /// Pack scale, 1..=8.
    pub scale: u32,
    /// CHR pages to render (duplicates ignored, output sorted).
    pub pages: &'a [u8],
    /// NES colour indices for sub-palette entries 1..=3; `None` = [`GRAY_RAMP`].
    pub colors: Option<[u8; 3]>,
}

/// Rendered template: sheets plus the manifest.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct TemplateOutput {
    /// `(relative path, PNG bytes)` per page.
    pub sheets: Vec<(String, Vec<u8>)>,
    /// `pack.json` text.
    pub pack_json: String,
}

impl TemplateOutput {
    /// All files to write: `pack.json`, the sheets and [`MARKER_FILE`].
    #[must_use]
    pub fn into_files(self) -> Vec<(String, Vec<u8>)> {
        let mut out = vec![(PACK_MANIFEST.to_string(), self.pack_json.into_bytes())];
        out.extend(self.sheets);
        out.push((MARKER_FILE.to_string(), MARKER_TEXT.as_bytes().to_vec()));
        out
    }
}

/// Template / recorder output failure.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum TemplateError {
    Scale(u32),
    NoPages,
    Page(u8),
    ChrTooShort { page: u8, len: usize },
    Png(PngError),
    Json(String),
}

impl fmt::Display for TemplateError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            TemplateError::Scale(s) => write!(f, "scale {s} out of range (1..={MAX_SCALE})"),
            TemplateError::NoPages => write!(f, "nothing to write: no pages selected / recorded"),
            TemplateError::Page(p) => {
                write!(f, "CHR page {p} out of range (0..={})", CHR_PAGES - 1)
            }
            TemplateError::ChrTooShort { page, len } => write!(
                f,
                "CHR image is {len} bytes; page {page} needs {} bytes",
                (usize::from(*page) + 1) * crate::chr::CHR_PAGE_LEN
            ),
            TemplateError::Png(e) => write!(f, "{e}"),
            TemplateError::Json(e) => write!(f, "pack.json encode failed: {e}"),
        }
    }
}

impl std::error::Error for TemplateError {}

impl From<PngError> for TemplateError {
    fn from(e: PngError) -> Self {
        TemplateError::Png(e)
    }
}

/// Relative path of a page sheet: `sheets/pageNN.png`, or for a palette
/// variant `sheets/pageNN.cAA-BB-CC.png` (NES colours in hex).
#[must_use]
pub fn sheet_file_name(page: u8, colors: Option<[u8; 3]>) -> String {
    match colors {
        None => format!("sheets/page{page:02}.png"),
        Some([a, b, c]) => format!("sheets/page{page:02}.c{a:02X}-{b:02X}-{c:02X}.png"),
    }
}

/// Encode a sheet with the ROM-derived tEXt marker.
///
/// # Errors
/// [`PngError`] from the encoder.
pub fn encode_template_sheet(img: &RgbaImage) -> Result<Vec<u8>, PngError> {
    encode_png_rgba(
        img.width,
        img.height,
        &img.rgba,
        &[(TEMPLATE_TEXT_KEY, TEMPLATE_TEXT_VALUE)],
    )
}

pub(crate) fn check_scale(scale: u32) -> Result<(), TemplateError> {
    if scale == 0 || scale > MAX_SCALE {
        Err(TemplateError::Scale(scale))
    } else {
        Ok(())
    }
}

pub(crate) fn nes_rgb3(colors: [u8; 3]) -> [[u8; 3]; 3] {
    colors.map(|c| MasterPalette::NES.rgb(c))
}

pub(crate) fn manifest_json(manifest: &PackManifest) -> Result<String, TemplateError> {
    serde_json::to_string_pretty(manifest)
        .map(|s| s + "\n")
        .map_err(|e| TemplateError::Json(e.to_string()))
}

pub(crate) fn page_sheet_entry(page: u8, colors: Option<[u8; 3]>) -> SheetEntry {
    SheetEntry {
        file: sheet_file_name(page, colors),
        layout: Some("page".to_string()),
        page: Some(u64::from(page)),
        colors: colors.map(|c| c.iter().map(|&v| u64::from(v)).collect()),
        scale: None,
    }
}

pub(crate) fn empty_manifest(name: &str, scale: u32) -> PackManifest {
    PackManifest {
        format: Some(PACK_FORMAT.to_string()),
        version: PACK_VERSION,
        name: name.to_string(),
        author: None,
        scale: u64::from(scale),
        alpha_threshold: None,
        palette: None,
        sheets: Vec::new(),
        tiles: Vec::new(),
        sprite_alpha: None,
        layers: Vec::new(),
        groups: None,
    }
}

/// Render full-page template sheets for `opts.pages` of `chr_rom`.
///
/// Every tile is painted (sub-palette 0 transparent, 1..=3 from
/// `opts.colors` or [`GRAY_RAMP`]) and nearest-upscaled by `opts.scale`.
///
/// # Errors
/// [`TemplateError`] for a bad scale, empty/out-of-range page list, a CHR
/// image too short for a page, or an encoder failure.
pub fn template_from_chr(
    chr_rom: &[u8],
    opts: &TemplateOptions<'_>,
) -> Result<TemplateOutput, TemplateError> {
    check_scale(opts.scale)?;
    let pages: BTreeSet<u8> = opts.pages.iter().copied().collect();
    if pages.is_empty() {
        return Err(TemplateError::NoPages);
    }
    let rgb = opts.colors.map_or(GRAY_RAMP, nes_rgb3);
    let mut manifest = empty_manifest(opts.name, opts.scale);
    let mut sheets = Vec::with_capacity(pages.len());
    for &page in &pages {
        if usize::from(page) >= CHR_PAGES {
            return Err(TemplateError::Page(page));
        }
        let bytes = chr_page(chr_rom, page).ok_or(TemplateError::ChrTooShort {
            page,
            len: chr_rom.len(),
        })?;
        let img = paint_page_sheet(bytes, opts.scale, |_| Some(rgb));
        sheets.push((sheet_file_name(page, None), encode_template_sheet(&img)?));
        manifest.sheets.push(page_sheet_entry(page, None));
    }
    Ok(TemplateOutput {
        sheets,
        pack_json: manifest_json(&manifest)?,
    })
}
