//! Sideview room layouts: decode, re-encode, and a solid-tile grid.
//!
//! A sideview is the byte stream the game turns into a side-scrolling room
//! (palace rooms, towns, caves, overworld encounter scenes). This module is
//! shared: the `palaces` module rebuilds and moves rooms with it, and the
//! `enemies` module uses [`Grid`] to find floor spots for enemies.
//!
//! Nothing here embeds ROM data. The one game table the grid needs (the
//! floor/ceiling patterns) is read from the player's ROM with
//! [`FloorTable::from_rom`]; object meanings are written down from how the
//! game behaves.
//!
//! # Format (what [`Sideview::parse`] understands)
//!
//! * A 4-byte header: byte 0 is the total length (header included); byte 1
//!   bit 7 selects the alternate object tiles and bits 6-5 are the page
//!   count minus one (one page is 16 columns, rooms have 1-4 pages); byte 2
//!   bit 7 is "no ceiling", bits 6-4 the ground type, bits 3-0 the starting
//!   floor pattern; byte 3 holds the palettes and, in bits 2-0, a shared
//!   background layout drawn first (0 = none).
//! * Then commands of 2 bytes (`YX`, `B`), or 3 bytes when `B == $0F` and
//!   the row is not 13 (a collectable item; the third byte is the item).
//!   `X` (low nibble of the first byte) advances the column cursor; `Y`
//!   (high nibble) is the row, with three special rows:
//!   * 13: a new floor pattern from this column on (`B` bit 7 = no ceiling,
//!     `B & $0F` = pattern);
//!   * 14: jump the cursor to the start of page `X & 3` (`B` unused); the
//!     next command's `X` then advances from there;
//!   * 15: an "extended" object (`B` high nibble = kind, low nibble = size).
//! * Rows 0-12 with `B < $10` are small fixed objects; with `B >= $10` the
//!   high nibble is a large object kind and the low nibble its size minus
//!   one (width or height, depending on the kind).
//!
//! Columns are absolute in [`Command::x`] (0-63). [`Sideview::encode`]
//! recomputes the cursor steps and inserts page jumps where needed, so
//! commands can be moved, added and removed freely.
//!
//! # Grid
//!
//! [`Sideview::grid`] replays the game's drawing order (floors column by
//! column, then objects in command order, later objects overwriting earlier
//! ones) on a 64 x 13 cell grid. It answers "is this cell solid", "where
//! can something stand", "where is the elevator", "which columns are open
//! to the bottom (drops)" and "which bottom cells are lava".

use std::fmt;

use crate::rom::Rom;
use crate::RandoError;

/// Rows in a sideview (row 12 is the bottom row).
pub const ROWS: usize = 13;
/// Columns in one page (one screen).
pub const PAGE_COLS: usize = 16;
/// Pages in the largest room.
pub const MAX_PAGES: usize = 4;
/// Columns in the largest room.
pub const MAX_COLS: usize = PAGE_COLS * MAX_PAGES;
/// Header length.
pub const HEADER_LEN: usize = 4;
/// Longest sideview the one-byte length field allows.
pub const MAX_LEN: usize = 255;

/// Row value of a floor command.
pub const ROW_FLOOR: u8 = 13;
/// Row value of a page jump.
pub const ROW_SKIP: u8 = 14;
/// Row value of an extended object.
pub const ROW_EXTENDED: u8 = 15;
/// `B` value that marks a 3-byte collectable command.
pub const COLLECTABLE: u8 = 0x0F;

/// CPU address (fixed bank) of the game's floor/ceiling pattern table.
pub const FLOOR_TABLE_ADDR: u16 = 0xC735;

/// Decode / encode failure.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum SideviewError {
    /// The length byte disagrees with the data or is out of range.
    BadLength(String),
    /// A command runs past the end.
    Truncated(usize),
    /// A command column is outside the room.
    Column(u8),
    /// The encoded room would not fit the one-byte length.
    TooLong(usize),
}

impl fmt::Display for SideviewError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            SideviewError::BadLength(m) => write!(f, "bad sideview length: {m}"),
            SideviewError::Truncated(at) => write!(f, "sideview command truncated at byte {at}"),
            SideviewError::Column(x) => write!(f, "sideview column {x} out of range"),
            SideviewError::TooLong(n) => write!(f, "sideview of {n} bytes exceeds 255"),
        }
    }
}

impl std::error::Error for SideviewError {}

impl From<SideviewError> for RandoError {
    fn from(e: SideviewError) -> Self {
        RandoError::Rom(e.to_string())
    }
}

/// One drawing command with an absolute column.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct Command {
    /// Absolute column (0-63).
    pub x: u8,
    /// Row 0-12, or [`ROW_FLOOR`] / [`ROW_EXTENDED`]. Page jumps are not
    /// kept as commands (they are regenerated by [`Sideview::encode`]).
    pub y: u8,
    /// Object byte.
    pub b: u8,
    /// Item id for a collectable (`b == $0F`, row < 13).
    pub item: Option<u8>,
}

impl Command {
    /// A plain object (or floor / extended command) at `(x, y)`.
    #[must_use]
    pub const fn new(x: u8, y: u8, b: u8) -> Command {
        Command {
            x,
            y,
            b,
            item: None,
        }
    }

    /// A collectable item at `(x, y)`.
    #[must_use]
    pub const fn collectable(x: u8, y: u8, item: u8) -> Command {
        Command {
            x,
            y,
            b: COLLECTABLE,
            item: Some(item),
        }
    }

    /// A floor-pattern change at column `x`.
    #[must_use]
    pub const fn floor(x: u8, value: u8) -> Command {
        Command::new(x, ROW_FLOOR, value)
    }

    /// Floor-pattern command?
    #[must_use]
    pub const fn is_floor(&self) -> bool {
        self.y == ROW_FLOOR
    }

    /// Extended (row 15) object?
    #[must_use]
    pub const fn is_extended(&self) -> bool {
        self.y == ROW_EXTENDED
    }

    /// Collectable item?
    #[must_use]
    pub const fn is_collectable(&self) -> bool {
        self.item.is_some()
    }

    /// Small fixed object (row 0-12, `b < $10`, not an item)?
    #[must_use]
    pub const fn is_small(&self) -> bool {
        self.y < ROW_FLOOR && self.b < 0x10 && self.item.is_none()
    }

    /// Large object (row 0-12, `b >= $10`)?
    #[must_use]
    pub const fn is_large(&self) -> bool {
        self.y < ROW_FLOOR && self.b >= 0x10
    }

    /// Large/extended object kind (`b` high nibble).
    #[must_use]
    pub const fn kind(&self) -> u8 {
        self.b >> 4
    }

    /// Large/extended object size parameter (`b` low nibble; size - 1).
    #[must_use]
    pub const fn size(&self) -> u8 {
        self.b & 0x0F
    }

    /// Encoded length (2 or 3 bytes).
    #[must_use]
    pub const fn encoded_len(&self) -> usize {
        if self.item.is_some() {
            3
        } else {
            2
        }
    }
}

/// A decoded room layout.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct Sideview {
    /// Header bytes (byte 0, the length, is rewritten on encode).
    pub header: [u8; HEADER_LEN],
    /// Commands in drawing order, with absolute columns.
    pub commands: Vec<Command>,
}

impl Sideview {
    /// Decode a sideview. `bytes` may be longer than the room (the length
    /// byte decides); it must not be shorter.
    pub fn parse(bytes: &[u8]) -> Result<Sideview, SideviewError> {
        Ok(Sideview::parse_with_offsets(bytes)?.0)
    }

    /// Decode a sideview and also return, per command, the byte offset of
    /// its first byte inside `bytes` (so a caller can patch a single byte,
    /// such as an item id at `offset + 2`, without re-encoding).
    pub fn parse_with_offsets(bytes: &[u8]) -> Result<(Sideview, Vec<usize>), SideviewError> {
        let len = *bytes
            .first()
            .ok_or_else(|| SideviewError::BadLength("empty".into()))? as usize;
        if len < HEADER_LEN {
            return Err(SideviewError::BadLength(format!("{len} < header")));
        }
        if bytes.len() < len {
            return Err(SideviewError::BadLength(format!(
                "length byte {len} but only {} bytes",
                bytes.len()
            )));
        }
        let data = &bytes[..len];
        let mut header = [0u8; HEADER_LEN];
        header.copy_from_slice(&data[..HEADER_LEN]);
        let mut commands = Vec::new();
        let mut offsets = Vec::new();
        let mut i = HEADER_LEN;
        let mut cursor: u16 = 0;
        while i < len {
            let mut a = data[i];
            if a >> 4 == ROW_SKIP {
                // Page jump: two bytes, then the next command's step counts
                // from the start of that page.
                cursor = u16::from(a & 3) * PAGE_COLS as u16;
                i += 2;
                if i >= len {
                    break;
                }
                a = data[i];
                if a >> 4 == ROW_SKIP {
                    continue;
                }
            }
            let start = i;
            let b = *data.get(i + 1).ok_or(SideviewError::Truncated(i))?;
            cursor += u16::from(a & 0x0F);
            let y = a >> 4;
            let x = u8::try_from(cursor).map_err(|_| SideviewError::Column(0xFF))?;
            if y != ROW_FLOOR && b == COLLECTABLE {
                let item = *data.get(i + 2).ok_or(SideviewError::Truncated(i))?;
                commands.push(Command::collectable(x, y, item));
                i += 3;
            } else {
                commands.push(Command::new(x, y, b));
                i += 2;
            }
            offsets.push(start);
        }
        Ok((Sideview { header, commands }, offsets))
    }

    /// Encode, recomputing the length byte, the column steps and any page
    /// jumps. Commands are written in their current order; a command whose
    /// column is behind the cursor or more than 15 columns ahead gets a page
    /// jump first.
    pub fn encode(&self) -> Result<Vec<u8>, SideviewError> {
        let mut out = Vec::with_capacity(HEADER_LEN + 2 * self.commands.len());
        out.extend_from_slice(&self.header);
        let mut cursor: u16 = 0;
        for c in &self.commands {
            let x = u16::from(c.x);
            if x >= MAX_COLS as u16 {
                return Err(SideviewError::Column(c.x));
            }
            if x < cursor || x - cursor > 15 {
                let page = x / PAGE_COLS as u16;
                out.push((ROW_SKIP << 4) | page as u8);
                out.push(0);
                cursor = page * PAGE_COLS as u16;
            }
            let step = (x - cursor) as u8;
            out.push((c.y << 4) | step);
            out.push(c.b);
            if let Some(item) = c.item {
                out.push(item);
            }
            cursor = x;
        }
        if out.len() > MAX_LEN {
            return Err(SideviewError::TooLong(out.len()));
        }
        out[0] = out.len() as u8;
        Ok(out)
    }

    /// Encoded length without encoding.
    #[must_use]
    pub fn encoded_len(&self) -> usize {
        self.encode().map_or(usize::MAX, |v| v.len())
    }

    /// Pages (1-4) from header byte 1.
    #[must_use]
    pub fn pages(&self) -> u8 {
        ((self.header[1] >> 5) & 3) + 1
    }

    /// Width in columns.
    #[must_use]
    pub fn width(&self) -> usize {
        usize::from(self.pages()) * PAGE_COLS
    }

    /// Alternate object tiles (header byte 1 bit 7).
    #[must_use]
    pub fn alternate_objects(&self) -> bool {
        self.header[1] & 0x80 != 0
    }

    /// Starting floor pattern (header byte 2 bits 3-0).
    #[must_use]
    pub fn start_floor(&self) -> u8 {
        self.header[2] & 0x0F
    }

    /// No ceiling at the start (header byte 2 bit 7).
    #[must_use]
    pub fn start_no_ceiling(&self) -> bool {
        self.header[2] & 0x80 != 0
    }

    /// Ground type (header byte 2 bits 6-4).
    #[must_use]
    pub fn ground_type(&self) -> u8 {
        (self.header[2] >> 4) & 7
    }

    /// Shared background layout index (header byte 3 bits 2-0, 0 = none).
    #[must_use]
    pub fn background_map(&self) -> u8 {
        self.header[3] & 7
    }

    /// Column of the elevator (extended kind 5), if any.
    #[must_use]
    pub fn elevator_column(&self) -> Option<u8> {
        self.commands
            .iter()
            .find(|c| c.is_extended() && c.kind() == 5)
            .map(|c| c.x)
    }

    /// Page holding the elevator, if any.
    #[must_use]
    pub fn elevator_page(&self) -> Option<u8> {
        self.elevator_column().map(|x| x / PAGE_COLS as u8)
    }

    /// Collectables as `(command index, command)`.
    pub fn collectables(&self) -> impl Iterator<Item = (usize, &Command)> {
        self.commands
            .iter()
            .enumerate()
            .filter(|(_, c)| c.is_collectable())
    }

    /// Mirror the room left-to-right inside its own width: columns are
    /// reflected (wide objects keep their extent), floor changes are moved so
    /// the same patterns cover the mirrored columns. Item rooms, elevators
    /// and doors move with their columns. Small objects that face a
    /// direction are not swapped (the caller decides).
    #[must_use]
    pub fn mirrored(&self, set: ObjectSet) -> Sideview {
        let w = self.width() as i32;
        let mut floors: Vec<(i32, u8)> = Vec::new();
        let mut objs: Vec<Command> = Vec::new();
        for c in &self.commands {
            if c.is_floor() {
                floors.push((i32::from(c.x), c.b));
            } else {
                let span = i32::from(object_width(c, set));
                let nx = (w - i32::from(c.x) - span).clamp(0, w - 1);
                let mut n = *c;
                n.x = nx as u8;
                objs.push(n);
            }
        }
        // Floor runs: pattern p covers [x_i, x_{i+1}); mirrored it covers
        // (w - x_{i+1}, w - x_i], i.e. starts at w - x_{i+1}.
        let mut runs: Vec<(i32, u8)> = Vec::new();
        let mut cur = self.header[2] & 0x8F;
        let mut start = 0;
        for &(x, v) in &floors {
            if x > start {
                runs.push((start, cur));
            }
            start = x;
            cur = v;
        }
        runs.push((start, cur));
        let mut header = self.header;
        let mut new_floors: Vec<Command> = Vec::new();
        // The last run becomes the first (header) run.
        let mut ends: Vec<(i32, i32, u8)> = Vec::new();
        for (i, &(s, v)) in runs.iter().enumerate() {
            let e = runs.get(i + 1).map_or(w, |r| r.0);
            ends.push((w - e, w - s, v));
        }
        ends.sort_by_key(|r| r.0);
        if let Some(&(_, _, v)) = ends.first() {
            header[2] = (header[2] & 0x70) | (v & 0x8F);
        }
        for &(s, _, v) in ends.iter().skip(1) {
            if s < w {
                new_floors.push(Command::floor(s as u8, v));
            }
        }
        let mut commands: Vec<Command> = objs;
        commands.extend(new_floors);
        // The game only honours a floor change if no earlier command sits
        // at a later column, so sort by column with floors first in each
        // column. Overlapping objects keep their relative order only when
        // they start in the same column (the same rule the encoder of any
        // re-laid-out room has to live with).
        commands.sort_by_key(|c| (c.x, u8::from(!c.is_floor())));
        Sideview { header, commands }
    }

    /// Solid-tile grid (see [`Grid`]).
    #[must_use]
    pub fn grid(&self, set: ObjectSet, floors: &FloorTable) -> Grid {
        Grid::build(self, set, floors)
    }
}

/// Which object meanings apply (the game has one object set per area kind).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum ObjectSet {
    /// Palaces 1-6 (bank 4).
    Palace,
    /// The Great Palace (bank 5).
    GreatPalace,
    /// Towns, caves and outdoor scenes. Large objects are treated as solid
    /// and small ones as decoration; good enough for floor finding.
    Other,
}

/// What a grid cell holds, as far as movement is concerned.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Cell {
    /// Nothing; can be walked or fallen through.
    Empty,
    /// Solid wall or floor.
    Solid,
    /// Solid but can be broken (stab or step, depending on the block).
    Breakable,
    /// Bridge that crumbles after being stood on.
    Crumble,
    /// Looks like a wall but can be walked through.
    FalseWall,
    /// Lava or water that hurts or kills.
    Lava,
}

impl Cell {
    /// Blocks movement / can be stood on.
    #[must_use]
    pub const fn is_solid(self) -> bool {
        matches!(self, Cell::Solid | Cell::Breakable | Cell::Crumble)
    }
}

/// The game's floor/ceiling patterns: per pattern 0-15, two mask bytes
/// whose bits say which of rows 0-11 are drawn solid. Read from the ROM.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct FloorTable {
    masks: [[u8; 2]; 16],
}

impl FloorTable {
    /// Read the pattern table from the fixed bank of `rom`.
    pub fn from_rom(rom: &Rom) -> Result<FloorTable, RandoError> {
        let mut masks = [[0u8; 2]; 16];
        for (i, m) in masks.iter_mut().enumerate() {
            let a = FLOOR_TABLE_ADDR + 2 * i as u16;
            *m = [rom.read_cpu(7, a)?, rom.read_cpu(7, a + 1)?];
        }
        Ok(FloorTable { masks })
    }

    /// Build from explicit masks (tests, synthetic ROMs).
    #[must_use]
    pub const fn from_masks(masks: [[u8; 2]; 16]) -> FloorTable {
        FloorTable { masks }
    }

    /// Is `row` (0-11) solid in `pattern`? Row r of the top half is bit
    /// `6 - r` of the first byte, row r of the bottom half bit `6 - (r - 6)`
    /// of the second. (The game reads a 3-bit window to pick edge tiles;
    /// only the middle bit decides solidity.)
    #[must_use]
    pub fn row_solid(&self, pattern: u8, row: usize) -> bool {
        let m = self.masks[usize::from(pattern & 0x0F)];
        match row {
            0..=5 => m[0] & (0x40 >> row) != 0,
            6..=11 => m[1] & (0x40 >> (row - 6)) != 0,
            _ => true,
        }
    }
}

/// Columns an object covers horizontally (for mirroring and spans).
#[must_use]
pub fn object_width(c: &Command, set: ObjectSet) -> u8 {
    if c.is_floor() || c.is_collectable() {
        return 1;
    }
    if c.is_extended() {
        return match c.kind() {
            5 => 2,
            _ => c.size() + 1,
        };
    }
    if c.is_small() {
        return match (set, c.b) {
            (_, 7 | 8) => 2,
            (ObjectSet::Palace, 0x0A..=0x0E) => 2,
            (ObjectSet::GreatPalace, 0x0B..=0x0E) => 2,
            _ => 1,
        };
    }
    match horizontal_or_vertical(c, set) {
        Shape::Horizontal { .. } => c.size() + 1,
        Shape::Vertical => 1,
    }
}

enum Shape {
    Horizontal { height: u8 },
    Vertical,
}

fn horizontal_or_vertical(c: &Command, set: ObjectSet) -> Shape {
    let k = c.kind();
    match set {
        ObjectSet::Palace => match k {
            1..=5 => Shape::Horizontal { height: 1 },
            6..=0x0A => Shape::Horizontal { height: 2 },
            _ => Shape::Vertical,
        },
        ObjectSet::GreatPalace => match k {
            1..=7 => Shape::Horizontal { height: 1 },
            8..=0x0C => Shape::Horizontal { height: 2 },
            _ => Shape::Vertical,
        },
        ObjectSet::Other => match k {
            1..=7 => Shape::Horizontal { height: 1 },
            8..=0x0C => Shape::Horizontal { height: 2 },
            _ => Shape::Vertical,
        },
    }
}

fn large_cell(k: u8, set: ObjectSet) -> Cell {
    match set {
        // 1 bricks, 2 breakable, 3 pedestal, 4 crumbling bridge, 5 bridge,
        // 6 bricks, 7 curtains, 8 breakable, 9 false bricks, A breakable,
        // B column, C-E background.
        ObjectSet::Palace => match k {
            1 | 3 | 5 | 6 => Cell::Solid,
            2 | 8 | 0x0A => Cell::Breakable,
            4 => Cell::Crumble,
            9 => Cell::FalseWall,
            _ => Cell::Empty,
        },
        // 1 bricks, 2 breakable, 3 pedestal, 4 castle bricks, 5 carpet,
        // 6 crumbling bridge, 7 bridge, 8 bricks, 9 curtains, A false
        // bricks, B/C breakable, D barrier background, E column, F misc.
        ObjectSet::GreatPalace => match k {
            1 | 3 | 4 | 5 | 7 | 8 => Cell::Solid,
            2 | 0x0B | 0x0C => Cell::Breakable,
            6 => Cell::Crumble,
            0x0A => Cell::FalseWall,
            _ => Cell::Empty,
        },
        ObjectSet::Other => Cell::Solid,
    }
}

/// The room as cells: [`MAX_COLS`] x [`ROWS`], plus a few facts the game
/// keeps outside the tile map.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Grid {
    width: usize,
    cells: Vec<Cell>,
    /// Elevator column, if the room has one.
    pub elevator: Option<u8>,
    /// Locked-door columns.
    pub doors: Vec<u8>,
    /// Collectables as `(x, y, item)`.
    pub items: Vec<(u8, u8, u8)>,
}

impl Grid {
    fn build(sv: &Sideview, set: ObjectSet, floors: &FloorTable) -> Grid {
        let width = sv.width();
        let mut g = Grid {
            width,
            cells: vec![Cell::Empty; MAX_COLS * ROWS],
            elevator: None,
            doors: Vec::new(),
            items: Vec::new(),
        };
        // Pass 1: floors and ceilings, column by column, the way the game
        // sweeps: every command moves the sweep up to its column; a floor
        // change takes effect only when the sweep reaches its column exactly
        // (one that is behind the sweep is ignored by the game too).
        let mut pattern = sv.start_floor();
        let mut no_ceiling = sv.start_no_ceiling();
        let mut sweep = 0usize;
        let draw = |g: &mut Grid, x: usize, pattern: u8, no_ceiling: bool| {
            let top = if no_ceiling { 2 } else { 0 };
            for row in top..ROWS - 1 {
                if floors.row_solid(pattern, row) {
                    g.set(x, row, Cell::Solid);
                }
            }
            g.set(x, ROWS - 1, Cell::Solid);
        };
        for c in &sv.commands {
            let cx = usize::from(c.x);
            if cx < sweep {
                continue;
            }
            while sweep < cx && sweep < MAX_COLS {
                draw(&mut g, sweep, pattern, no_ceiling);
                sweep += 1;
            }
            if c.is_floor() {
                pattern = c.b & 0x0F;
                no_ceiling = c.b & 0x80 != 0;
            }
            if sweep < MAX_COLS {
                draw(&mut g, sweep, pattern, no_ceiling);
                sweep += 1;
            }
        }
        while sweep < MAX_COLS {
            draw(&mut g, sweep, pattern, no_ceiling);
            sweep += 1;
        }
        // Pass 2: objects in order.
        for c in sv.commands.iter().filter(|c| !c.is_floor()) {
            let x = usize::from(c.x);
            let y = usize::from(c.y);
            if c.is_collectable() {
                g.items.push((c.x, c.y, c.item.unwrap_or(0)));
                continue;
            }
            if c.is_extended() {
                match (set, c.kind()) {
                    (_, 5) => g.elevator = Some(c.x),
                    // Palace pit: clears whole columns.
                    (ObjectSet::Palace | ObjectSet::Other, 1) => {
                        for cx in x..=x + usize::from(c.size()) {
                            for row in 0..ROWS {
                                g.set(cx, row, Cell::Empty);
                            }
                        }
                    }
                    // Lava: bottom two rows (three in the Great Palace).
                    (_, 1..=4) => {
                        let depth = if set == ObjectSet::GreatPalace { 3 } else { 2 };
                        for cx in x..=x + usize::from(c.size()) {
                            for row in ROWS - depth..ROWS {
                                g.set(cx, row, Cell::Lava);
                            }
                        }
                    }
                    _ => {}
                }
                continue;
            }
            if c.is_small() {
                match (set, c.b) {
                    (ObjectSet::Palace, 5 | 6) | (ObjectSet::GreatPalace, 5) => g.doors.push(c.x),
                    (ObjectSet::GreatPalace, 6) => {
                        for row in 0..ROWS {
                            g.set(x, row, Cell::Empty);
                        }
                    }
                    _ => {}
                }
                continue;
            }
            let cell = large_cell(c.kind(), set);
            match horizontal_or_vertical(c, set) {
                Shape::Horizontal { height } => {
                    for cx in x..=x + usize::from(c.size()) {
                        for row in y..y + usize::from(height) {
                            g.set(cx, row, cell);
                        }
                    }
                }
                Shape::Vertical => {
                    for row in y..=y + usize::from(c.size()) {
                        g.set(x, row, cell);
                    }
                }
            }
        }
        g
    }

    fn set(&mut self, x: usize, y: usize, c: Cell) {
        if x < MAX_COLS && y < ROWS {
            self.cells[y * MAX_COLS + x] = c;
        }
    }

    /// Room width in columns.
    #[must_use]
    pub fn width(&self) -> usize {
        self.width
    }

    /// Cell at `(x, y)`; outside the room counts as [`Cell::Solid`].
    #[must_use]
    pub fn cell(&self, x: usize, y: usize) -> Cell {
        if x >= self.width || y >= ROWS {
            Cell::Solid
        } else {
            self.cells[y * MAX_COLS + x]
        }
    }

    /// Solid at `(x, y)`?
    #[must_use]
    pub fn is_solid(&self, x: usize, y: usize) -> bool {
        self.cell(x, y).is_solid()
    }

    /// Rows in column `x` where something can stand: the cell is not solid
    /// and the one below is. Top to bottom.
    #[must_use]
    pub fn standable_rows(&self, x: usize) -> Vec<usize> {
        (0..ROWS - 1)
            .filter(|&y| {
                !self.is_solid(x, y) && self.cell(x, y) != Cell::Lava && self.is_solid(x, y + 1)
            })
            .collect()
    }

    /// The row something falling from `y` in column `x` lands on (the last
    /// non-solid row above a solid one), or `None` if it falls out of the
    /// bottom or into lava.
    #[must_use]
    pub fn landing_row(&self, x: usize, y: usize) -> Option<usize> {
        let mut row = y;
        while row + 1 < ROWS {
            if self.is_solid(x, row + 1) {
                return Some(row);
            }
            if self.cell(x, row + 1) == Cell::Lava {
                return None;
            }
            row += 1;
        }
        None
    }

    /// Columns whose bottom row is open (Link falls out of the room).
    #[must_use]
    pub fn open_bottom_columns(&self) -> Vec<usize> {
        (0..self.width)
            .filter(|&x| self.cell(x, ROWS - 1) == Cell::Empty)
            .collect()
    }

    /// Pages with at least one open-bottom column.
    #[must_use]
    pub fn drop_pages(&self) -> Vec<u8> {
        let mut v: Vec<u8> = self
            .open_bottom_columns()
            .into_iter()
            .map(|x| (x / PAGE_COLS) as u8)
            .collect();
        v.dedup();
        v
    }

    /// Lowest standable row in column `x` reachable by falling from the
    /// top-most open row (handy for "where does an entering player land").
    #[must_use]
    pub fn ground_row(&self, x: usize) -> Option<usize> {
        self.standable_rows(x).last().copied()
    }

    /// Text picture (`#` solid, `%` breakable, `=` crumble, `~` lava, `:`
    /// false wall, `E` elevator column top, `I` item), one line per row.
    #[must_use]
    pub fn render(&self) -> String {
        let mut s = String::new();
        for y in 0..ROWS {
            for x in 0..self.width {
                let ch = if self
                    .items
                    .iter()
                    .any(|&(ix, iy, _)| usize::from(ix) == x && usize::from(iy) == y)
                {
                    'I'
                } else if y == 0 && self.elevator.map(usize::from) == Some(x) {
                    'E'
                } else {
                    match self.cell(x, y) {
                        Cell::Empty => '.',
                        Cell::Solid => '#',
                        Cell::Breakable => '%',
                        Cell::Crumble => '=',
                        Cell::FalseWall => ':',
                        Cell::Lava => '~',
                    }
                };
                s.push(ch);
            }
            s.push('\n');
        }
        s
    }
}

/// Read and decode the sideview at CPU `(bank, addr)` (a `$C000+` address
/// reads the fixed bank). Returns the decoded room and its raw bytes.
pub fn read_at(rom: &Rom, bank: u8, addr: u16) -> Result<(Sideview, Vec<u8>), RandoError> {
    let len = usize::from(rom.read_cpu(bank, addr)?);
    let off = rom.cpu_offset(bank, addr)?;
    let raw = rom.read_slice(off, len.max(1))?.to_vec();
    let sv = Sideview::parse(&raw)?;
    Ok((sv, raw))
}

#[cfg(test)]
mod tests {
    use super::*;

    /// A made-up pattern table: pattern 0 = ceiling row 0 + floor rows
    /// 10-11, pattern 15 = all solid, pattern 1 = floor rows 8-11.
    fn floors() -> FloorTable {
        let mut m = [[0u8; 2]; 16];
        m[0] = [0x40, 0x06];
        m[1] = [0x40, 0x1E];
        m[15] = [0x7E, 0x7E];
        FloorTable::from_masks(m)
    }

    fn room() -> Vec<u8> {
        // 4 pages, palace header, a 3-wide brick row at (5, 7), an item at
        // (20, 9), floor change to pattern 15 at column 40, elevator at 39,
        // a pit 2 wide at column 50, and a page jump.
        let sv = Sideview {
            header: [0, 0x60, 0x00, 0x00],
            commands: vec![
                Command::new(5, 7, 0x12),
                Command::collectable(20, 9, 0x08),
                Command::new(39, ROW_EXTENDED, 0x50),
                Command::floor(40, 0x0F),
                Command::floor(44, 0x00),
                Command::new(50, ROW_EXTENDED, 0x11),
            ],
        };
        sv.encode().unwrap()
    }

    #[test]
    fn parse_encode_round_trip() {
        let raw = room();
        assert_eq!(usize::from(raw[0]), raw.len());
        let sv = Sideview::parse(&raw).unwrap();
        assert_eq!(sv.pages(), 4);
        assert_eq!(sv.commands.len(), 6);
        assert_eq!(sv.commands[1], Command::collectable(20, 9, 0x08));
        assert_eq!(sv.encode().unwrap(), raw);
        assert_eq!(sv.elevator_page(), Some(2));
    }

    #[test]
    fn page_jumps_are_inserted_and_understood() {
        let sv = Sideview {
            header: [0, 0x60, 0, 0],
            commands: vec![Command::new(2, 3, 0x10), Command::new(40, 3, 0x10)],
        };
        let raw = sv.encode().unwrap();
        // header, cmd, jump to page 2, cmd with step 8
        assert_eq!(&raw[4..], &[0x32, 0x10, 0xE2, 0x00, 0x38, 0x10]);
        assert_eq!(
            Sideview::parse(&raw).unwrap(),
            Sideview {
                header: [10, 0x60, 0, 0],
                ..sv
            }
        );
    }

    #[test]
    fn offsets_point_at_commands() {
        let raw = room();
        let (sv, offs) = Sideview::parse_with_offsets(&raw).unwrap();
        let (i, _) = sv.collectables().next().unwrap();
        assert_eq!(raw[offs[i] + 1], COLLECTABLE);
        assert_eq!(raw[offs[i] + 2], 0x08);
    }

    #[test]
    fn grid_floors_objects_pits() {
        let sv = Sideview::parse(&room()).unwrap();
        let g = sv.grid(ObjectSet::Palace, &floors());
        assert_eq!(g.width(), 64);
        // pattern 0: ceiling row 0, floor rows 10-12
        assert!(g.is_solid(0, 0));
        assert!(!g.is_solid(0, 5));
        assert!(g.is_solid(0, 10) && g.is_solid(0, 11) && g.is_solid(0, 12));
        // bricks at row 7, columns 5-7
        assert!(g.is_solid(5, 7) && g.is_solid(7, 7) && !g.is_solid(8, 7));
        // all solid at 40-43, back to pattern 0 at 44
        assert!(g.is_solid(41, 5));
        assert!(!g.is_solid(44, 5));
        // pit clears columns 50-51 completely
        assert!(!g.is_solid(50, 12) && !g.is_solid(51, 0) && g.is_solid(52, 12));
        assert_eq!(g.drop_pages(), vec![3]);
        assert_eq!(g.elevator, Some(39));
        assert_eq!(g.items, vec![(20, 9, 8)]);
        assert_eq!(g.standable_rows(0), vec![9]);
        assert_eq!(g.landing_row(6, 0), Some(6));
        assert_eq!(g.landing_row(50, 0), None);
        assert!(g.render().lines().count() == ROWS);
    }

    #[test]
    fn no_ceiling_leaves_top_rows_open() {
        let sv = Sideview {
            header: [0, 0x00, 0x8F, 0],
            commands: vec![],
        };
        let g = sv.grid(ObjectSet::Palace, &floors());
        assert!(!g.is_solid(3, 0) && !g.is_solid(3, 1) && g.is_solid(3, 2));
    }

    #[test]
    fn mirror_reflects_columns_and_floors() {
        let sv = Sideview::parse(&room()).unwrap();
        let m = sv.mirrored(ObjectSet::Palace);
        let a = sv.grid(ObjectSet::Palace, &floors());
        let b = m.grid(ObjectSet::Palace, &floors());
        for x in 0..64 {
            for y in 0..ROWS {
                assert_eq!(a.cell(x, y), b.cell(63 - x, y), "({x},{y})");
            }
        }
        assert_eq!(
            m.mirrored(ObjectSet::Palace)
                .grid(ObjectSet::Palace, &floors()),
            a
        );
    }

    #[test]
    fn errors() {
        assert!(Sideview::parse(&[]).is_err());
        assert!(Sideview::parse(&[2, 0]).is_err());
        assert!(Sideview::parse(&[8, 0, 0, 0]).is_err());
        assert!(matches!(
            Sideview::parse(&[6, 0, 0, 0, 0x30, 0x0F]),
            Err(SideviewError::Truncated(4))
        ));
        let long = Sideview {
            header: [0; 4],
            commands: vec![Command::new(0, 1, 0x10); 200],
        };
        assert!(matches!(long.encode(), Err(SideviewError::TooLong(_))));
    }
}
